[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
credit_score_calculator = "6S5riJKdh8eLBbwE7qWpReRoN9LU14sCXz3WobkVebCc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/sanketmokashi/projects/dapps/credit-score-calculator/user.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
